core/urls.py
from django.urls import path
from .views import (
    HomeView, 
    checkoutView, 
    ItemDetailView, 
    OrderSummaryView, 
    add_to_cart, 
    remove_from_cart, 
    remove_single_item_from_cart
    )


app_name = "core"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("checkout/", checkoutView.as_view(), name="checkout"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("product/<int:pk>/", ItemDetailView.as_view(), name="product"),
    path("add-to-cart/<int:pk>/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<int:pk>/", remove_from_cart, name="remove-from-cart"),
    path("remove-item-from-cart/<int:pk>/", remove_single_item_from_cart, name="remove-single-item-from-cart"),
]

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


CATERGORY_CHOICES = (("S", "Shirt"), ("SW", "Sport Wear"), ("OW", "Outwear"))

LABEL_CHOICES = (("P", "primary"), ("S", "secondary"), ("F", "danger"))


class Item(models.Model):
    title = models.CharField(max_length=50)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATERGORY_CHOICES, max_length=50, default="S")
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default="P")
    description = models.TextField(
        default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem id asperiores soluta aut sunt, recusandae sit iusto?"
    )

    def __str__(self):
        return self.title

    def get_percentage_saved(self):
        saved = self.price - self.discount_price
        percentage_saved = round(saved/self.price * 100)
        return percentage_saved

    def  get_absolute_url(self):
        return reverse("core:product", kwargs={"pk": self.pk})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"pk": self.pk})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"pk": self.pk})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_price(self):
        return round(self.quantity * self.item.price, 2)
    
    def get_total_discount_price(self):
        return round(self.quantity * self.item.discount_price, 2)
        
    def get_amount_saved(self):
        saved = round(self.get_total_price() - self.get_total_discount_price())
        return saved
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return round(self.get_total_price())
    
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return round(total, 2)
    
    def count(self):
        return self.items.count()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}

    {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>

<body>
    {% include 'navbar.html' %}


    <div class="mt-5 pt-4">

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

    </div>

    {% block content %}
    {% endblock content %}


    {% block extra_body %}
    {% endblock %}
    <!--Footer-->
    {% include 'footer.html' %}

    <!-- SCRIPTS -->
    {% include 'scripts.html' %}
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}


{% block content %}

<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container wow fadeIn">

    <!-- Heading -->
    <h2 class="my-5 h2 text-center">Checkout form</h2>

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-md-8 mb-4">

        <!--Card-->
        <div class="card">

          <!--Card content-->
          <form class="card-body">
            {% csrf_token %}
            <!--Grid row-->

              <!--Grid column-->

          
            <!--address-->
            <div class="md-form mb-5">
                     {{ form.street_address }}
              <label for="address" class="">Address</label>
            </div>

            <!--address-2-->
            <div class="md-form mb-5">
              {{ form.city }}
              <label for="address-2" class="">Address 2 (optional)</label>
            </div>

            <!--Grid row-->
            <div class="row">

              <!--Grid column-->
              <div class="col-lg-4 col-md-12 mb-4">

                <label for="country">Country</label>
                <select class="custom-select d-block w-100" id="country" required>
                  <option value="">Choose...</option>
                  <option>United States</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4">

                <label for="state">State</label>
                <select class="custom-select d-block w-100" id="state" required>
                  <option value="">Choose...</option>
                  <option>California</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4">

                <label for="zip">Zip</label>
                 {{ form.zip }} 
                <div class="invalid-feedback">
                  Zip code required.
                </div>

              </div>
              <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>

            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="same-address">
              <label class="custom-control-label" for="same-address">Shipping address is the same as my billing
                address</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>

            <hr>

            <div class="d-block my-3">
               {% for value, text in form.payment_opttioin.choices %}
            
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="{{ name }}" type="radio" class="custom-control-input" checked required>
                <label class="custom-control-label" for="{{name}}">{{name}}</label>
              </div>
            {% endfor %}
            </div>

            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>

        </div>
        <!--/.Card-->

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-4 mb-4">

        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">3</span>
        </h4>

        <!-- Cart -->
        <ul class="list-group mb-3 z-depth-1">
          {% for order_item in object.items.all %}
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">{{ order_item.item.title }}</h6>
              {% comment %} <small class="text-muted">Brief description</small> {% endcomment %}
            </div>
            <span class="text-muted">${{ order_item.item.price }}</span>
          </li>

          {% endfor %}




          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">-$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$ {{object.get_total }}</strong>
          </li>
        </ul>
        <!-- Cart -->

        <!-- Promo code -->
        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username"
              aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
            </div>
          </div>
        </form>
        <!-- Promo code -->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a>

        <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="" target="_blank"> techknights.com </a>
    </div>
    <!--/.Copyright-->

</footer>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--Main layout-->
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">


        {% for item in object_list %}
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card image-->
            <div class="view overlay">
              <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                alt="">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }} " class="dark-grey-text">{{ item.title }}
                
                  </a>
                </strong>
              </h5>
              <!-- <h5>&#8358;<del>{{ item.price }}</del></h5> -->

              <h4 class="font-weight-bold blue-text">

                {% if item.discount_price %}
                <strong>${{ item.discount_price }}</strong>
    <span class="badge badge-pill badge-danger"> {{ item.get_percentage_saved}}%
                      off</span>

                {% else %}
                <strong>${{ item.price }}</strong>
                {% endif %}

              </h4>


            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>

        {% endfor %}


      </div>
      <!--Grid row-->

    </section>
    <!--Section: Products v.3-->

    {% if is_paginated %}
    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}

        <!--Arrow left-->
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.prev_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}"> {{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>


        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    <!--Pagination-->


  </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/item_list.html
{% extends 'base.html' %}


{% block content %}
<h1>
    All Products
</h1>
<div>
    {% for item  in items %}
    <p>
        {{ item }}
    </p>
    {% endfor %}

    {% endblock content %}
</div>

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
            <strong class="blue-text">Zeekara</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <!-- <li class="nav-item active">
                    <a class="nav-link waves -effect" href="">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link waves-effect">Products
                    </a>
                </li> -->

            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">

                {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a href={% url 'core:order-summary' %} class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                        <span class="badge red z-depth-1"> {{request.user|cart_item_count}}  </span>
                        <i class="fas fa-shopp  ing-cart"></i>  
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href=" {% url 'account_logout' %} ">
                        <span class=" clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link waves-effect" href=" {% url 'account_login' %} ">
                        <span class=" clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link waves-effect" href=" {% url 'account_signup' %} ">
                        <span class=" clearfix d-none d-sm-inline-block"> Sign Up </span>
                    </a>
                </li>
                {% endif %}

            </ul>

        </div>

    </div>
</nav>

templates/order_summary.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--Main layout-->
<main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="col"> {{ forloop.counter }} </th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.pk %}"><i
                                    class="fas fa-minus-circle mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a class="add_to_cart" href="{% url 'core:add-to-cart' order_item.item.pk %}"><i
                                    class=" fas fa-plus-circle ml-2"></i></a>
                        </td>

                        <td>
                            {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_price }} &nbsp
                            <span class="badge badge-success"> Saving ${{ order_item.get_amount_saved }} </span>
                            {% else %}
                            ${{ order_item.get_total_price }}</td>
                        {% endif %}
                        <a style="color:red" href="{% url 'core:remove-from-cart'  order_item.item.pk %}">
                            <i class="fas fa-trash float-right"></i>
                        </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5"> Your cart is Empty </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-warning float-right ml-2" href="/checkout">Proceed to checkout </a>
                            <a class="btn btn-primary float-right ml-2" href="/">Continue Shopping</a>
                        </td>
                    </tr>

                    {% endfor %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"> <b>Order Total</b></td>
                        <td colspan="4"> <b>${{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-warning float-right ml-2" href="/checkout">Proceed to checkout </a>
                            <a class="btn btn-primary float-right ml-2" href="/">Continue Shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>

    </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/product-page.html
{% extends 'base.html' %}
{% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">Category 2</span>
            </a>
            <a href="">
              <span class="badge blue mr-1">New</span>
            </a>
            <a href="">
              <span class="badge red mr-1">Bestseller</span>
            </a>
          </div>

          <p class="lead">
            <span class="mr-1">
              <del>$200</del>
            </span>
            <span>$100</span>
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
            sint voluptatibus!
            Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

          <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->

{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1"> {{ object.get_category_display }}</span>
            </a>
          </div>
          <h1>{{ object.title }}</h1>
          <p class="lead">

            {% if item.discount_price %}
            <span class="mr-1">
              <del>${{object.price}}</del>
            </span>
            <span>${{object.discount_price}}</span>
            {% else %}
            <span>${{object.price}}</span>
            {% endif %}




          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>{{item.description}}</p>

          {% comment %} <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form> {% endcomment %}

          <a href="{{ object.get_add_to_cart_url }}" class="add_to_cart btn btn-primary btn-md my-0 p">Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>

          <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">remove from cart
          </a>
        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->

{% endblock content %}

templates/scripts.html
{% load static %}
  <!-- JQuery -->
   <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
   <!-- Bootstrap tooltips -->
   <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
   <!-- Bootstrap core JavaScript -->
   <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
   <!-- MDB core JavaScript -->
   <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
   <!-- Initializations -->
   <script type="text/javascript">
       // Animations initialization
       new WOW().init();
   </script>